<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_title</name>
   <tag></tag>
   <elementGuidId>94602383-4354-49ed-87fa-dd2cb037f215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee70190e-603d-4313-ab4e-ef0d36300378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa535e55-f80f-4ea3-9f5a-86f27af5c52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>c4696938-3cab-4fa2-9c65-01e93a62732f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/form[1]/table[@class=&quot;table&quot;]/tbody[1]/tr[2]/td[1]/input[1]</value>
      <webElementGuid>4aa2c9eb-b7fa-4e0f-8881-cc4bd0cce4e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='title']</value>
      <webElementGuid>4a7733e5-af6f-4999-a7a4-e8fbda442c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/form/table/tbody/tr[2]/td/input</value>
      <webElementGuid>1432b7e9-4f51-4251-9cb6-6b20ad9852f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>921512c1-8b8d-4875-8bae-411a7465d3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'title']</value>
      <webElementGuid>ef78f5cf-350d-48c3-8514-f22308467a4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
