<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ISBN_isbn</name>
   <tag></tag>
   <elementGuidId>daa40ff4-cab3-4b8e-b27b-001651a50ba3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='isbn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;isbn&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8945d1ce-ffd9-429b-a190-3f0ed32a7921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a9e57cc-fbef-4c30-9c59-9199ac1bb578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isbn</value>
      <webElementGuid>0ab05ad9-d5e7-4451-a0b1-8a3bbe6c7071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/form[1]/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>b36c1b6b-ba38-4163-8329-5b5e796c5884</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='isbn']</value>
      <webElementGuid>2b5aa933-d378-4e04-a296-62f9fe6c7263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/form/table/tbody/tr/td/input</value>
      <webElementGuid>344098b8-9706-46b3-b40e-ea133834270c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>02e2afcf-6194-457e-adc4-a4500e25fd8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'isbn']</value>
      <webElementGuid>ebdd1a0f-3e37-4333-9d72-6dd4ca3351e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
