<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Publishers</name>
   <tag></tag>
   <elementGuidId>bb4634f6-87b0-4fd8-837e-15c94fe8c90d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.lead > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e802ec73-b6c5-4438-9049-425c25c7583b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>publisher_list.php</value>
      <webElementGuid>65c319e0-3f16-435e-ae85-18a8b30a8a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publishers</value>
      <webElementGuid>956bfd78-f4b8-4ad7-a1b4-6c494068a7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/p[@class=&quot;lead&quot;]/a[1]</value>
      <webElementGuid>dfa79f0a-88ee-45c9-bb41-677e430881f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/p/a</value>
      <webElementGuid>9197706e-a58e-4621-b550-96cbd66d6d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Publishers')]</value>
      <webElementGuid>0972af2d-b8ff-4448-ae83-421f81adeb42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Professional JavaScript for Web Developers, 3rd Edition'])[1]/preceding::a[1]</value>
      <webElementGuid>73d04b54-9a78-4b43-88ae-024ff658a535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Details'])[1]/preceding::a[1]</value>
      <webElementGuid>aaa90f16-d600-4f73-9f15-f497bdde5467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Publishers']/parent::*</value>
      <webElementGuid>3c4a027e-35d8-4ab0-b896-bfd44227b1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'publisher_list.php')])[2]</value>
      <webElementGuid>49c6ee2d-fe31-4909-80fb-1e4c705858c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>5b549094-2af4-490b-9be2-795447059bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'publisher_list.php' and (text() = 'Publishers' or . = 'Publishers')]</value>
      <webElementGuid>64c360c0-bce8-49f3-b20d-117aaf1b178e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
