<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Your cart is empty Please make sure you a_c3a7e9</name>
   <tag></tag>
   <elementGuidId>dac23438-3d0a-4454-8438-4ae12bfa5e2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.text-warning</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>cc07ecbc-811c-4933-adae-48eab35e92ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-warning</value>
      <webElementGuid>4b6d0161-a367-4cd6-8bff-fdce785e1f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your cart is empty! Please make sure you add some books in it!</value>
      <webElementGuid>8d24b276-8ed9-4bcd-954d-71cb4cf76072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/p[@class=&quot;text-warning&quot;]</value>
      <webElementGuid>8a9fa733-1d84-4593-ab5b-2dffb823ceb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/p</value>
      <webElementGuid>bbc875b8-3299-4fe2-a75f-9210daf39f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='projectworlds'])[1]/preceding::p[1]</value>
      <webElementGuid>30eb4068-fef1-4351-9f82-f7ade0bdb49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Login'])[1]/preceding::p[1]</value>
      <webElementGuid>c7baa6e3-a62d-47fb-bbfe-1ec4a2d66d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your cart is empty! Please make sure you add some books in it!']/parent::*</value>
      <webElementGuid>9d2fea1a-d9f7-4303-85ad-347022c2a612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>2d9c3136-e3ea-4ed2-9ff4-dcd4260bf324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Your cart is empty! Please make sure you add some books in it!' or . = 'Your cart is empty! Please make sure you add some books in it!')]</value>
      <webElementGuid>5b39288a-f968-4dfd-b06b-986fe13de453</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
