<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete_1</name>
   <tag></tag>
   <elementGuidId>2da559ba-e184-4b99-9569-2c52888fccfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/table/tbody/tr[10]/td[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>760accee-c933-48ed-b4bd-1dab4ccd84c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>admin_delete.php?bookisbn=978-0-7303-1484-4</value>
      <webElementGuid>759534f5-c446-41eb-a62b-b736fbc6050c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>efeb5d46-8872-4c83-88dd-59acf7fb4cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/table[@class=&quot;table&quot;]/tbody[1]/tr[10]/td[9]/a[1]</value>
      <webElementGuid>faea1e14-d8fe-4025-b995-0b3c769a08f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/table/tbody/tr[10]/td[9]/a</value>
      <webElementGuid>90aa05e3-cf7a-41fc-9a81-8e22f274a54d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Delete')])[9]</value>
      <webElementGuid>40dd7ebe-f496-496a-a107-b49f57f4b207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[9]/following::a[1]</value>
      <webElementGuid>0b5b07b1-0fa4-4e8c-b3a8-6aefe7a99679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wiley'])[2]/following::a[2]</value>
      <webElementGuid>90ff18ae-de4d-445a-84f7-4cf292045c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='projectworlds'])[1]/preceding::a[1]</value>
      <webElementGuid>d34dd498-6de6-409c-933e-7d3a9201ab60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Login'])[1]/preceding::a[2]</value>
      <webElementGuid>24ac428b-22dd-497f-853a-3176157d74b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'admin_delete.php?bookisbn=978-0-7303-1484-4')]</value>
      <webElementGuid>7880b131-7223-4982-9560-8200ac677b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[9]/a</value>
      <webElementGuid>5d2705df-90e1-4de5-a7d4-aeb0ff14e75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'admin_delete.php?bookisbn=978-0-7303-1484-4' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>e537f551-7172-4b0f-8150-8f8cc665e536</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
