<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Wrox</name>
   <tag></tag>
   <elementGuidId>b91d05b8-6394-483f-982b-6e7450b296ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>29b79a91-3868-4038-90dc-82a38f66b3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>bookPerPub.php?pubid=1</value>
      <webElementGuid>3f011d06-26c1-49cb-a0c4-0556b709c2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wrox</value>
      <webElementGuid>70db5f45-4c19-4fd8-ad6d-75f6e8de17e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[1]/li[1]/a[1]</value>
      <webElementGuid>caac19f0-d929-4d2f-bbc2-5a364aaa120f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/ul/li/a</value>
      <webElementGuid>094d8095-9c8a-4328-85f1-b0dbb8aa52e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Wrox')]</value>
      <webElementGuid>279c995a-a436-4ea3-9026-6f028b71c0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wiley'])[1]/preceding::a[1]</value>
      <webElementGuid>90ef353d-ffdf-402e-93c9-364e363adf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('O', &quot;'&quot;, 'Reilly Media')])[1]/preceding::a[2]</value>
      <webElementGuid>7819fc68-5b19-4c6e-9fc5-0f463ae7b277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wrox']/parent::*</value>
      <webElementGuid>55a8a7e7-0781-4c1f-91fb-9c35324b8843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'bookPerPub.php?pubid=1')]</value>
      <webElementGuid>bfbc26bf-7164-4086-bc84-b4d3314eaa3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/ul/li/a</value>
      <webElementGuid>3f999c2e-23fa-4571-91ff-6768cf9dcaa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'bookPerPub.php?pubid=1' and (text() = 'Wrox' or . = 'Wrox')]</value>
      <webElementGuid>05f4fcd6-63bc-4d84-b3bb-bc9aaa6a0447</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
